### DISCUSSION TITLE
Docker install is supposed to be easy. I can not make it work with scrumlr.io

### DISCUSSION THREAD

**Discussion by jbesclapez** [inovex/scrumlr.io#4321] [General]
Hello,
I have many containers running on my ubuntu server.  I usually use a docker compose and it works simply.
I am struggling to make this install for hours.
Can someone provide me a working docker compose?
Thanks

This below is not working : 

[version: "3.9"

services:
  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "ping", "nats", "-c", "2" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10

  database:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - /home/xxxx/Documents/Docker/scrumlr/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10

  scrumlr:
    image: scruml.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      SCRUMLR_SERVER_PORT: 8080
      SCRUMLR_SERVER_NATS_URL: "nats://nats:4222"
      SCRUMLR_SERVER_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable"
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
    depends_on:
      database:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - /home/xxxx/Documents/Docker/scrumlr/backend:/data

  frontend:
    image: scruml.io/frontend:latest
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:80"

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
](url)

**Comment by Lennart01** [comment]
```yaml
version: '3.8'

services:
  scrumlr-backend:
    restart: always
    image: scrumlr.io/scrumlr-server:v3.7.1
    command:
      - "/app/main"
      - "-disable-check-origin"
    environment:
      SCRUMLR_SERVER_PORT: "${SCRUMLR_SERVER_PORT}"
      SCRUMLR_SERVER_NATS_URL: "${SCRUMLR_SERVER_NATS_URL}"
      SCRUMLR_PRIVATE_KEY: "${SCRUMLR_PRIVATE_KEY}"
      SCRUMLR_SERVER_DATABASE_URL: "postgres://scrumlr:${POSTGRES_PASSWORD}@postgres:5432/scrumlr?sslmode=disable"
      SCRUMLR_AUTH_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      SCRUMLR_AUTH_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      SCRUMLR_AUTH_MICROSOFT_CLIENT_ID: "${MICROSOFT_CLIENT_ID}"
      SCRUMLR_AUTH_MICROSOFT_CLIENT_SECRET: "${MICROSOFT_CLIENT_SECRET}"
      SCRUMLR_FEEDBACK_WEBHOOK_URL: "${WEBHOOK_URL}"
      SCRUMLR_BASE_PATH: "${SCRUMLR_BASE_PATH}"
      SCRUMLR_INSECURE: "${SCRUMLR_INSECURE}"
      SCRUMLR_AUTH_GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      SCRUMLR_AUTH_GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      SCRUMLR_AUTH_AZURE_AD_TENANT_ID: "${AZURE_AD_TENANT_ID}"
      SCRUMLR_AUTH_AZURE_AD_CLIENT_ID: "${AZURE_AD_CLIENT_ID}"
      SCRUMLR_AUTH_AZURE_AD_CLIENT_SECRET: "${AZURE_AD_CLIENT_SECRET}"
      SCRUMLR_AUTH_APPLE_CLIENT_ID: "${APPLE_CLIENT_ID}"
      SCRUMLR_AUTH_APPLE_CLIENT_SECRET: "${APPLE_CLIENT_SECRET}"
      # SCRUMLR_CONFIG_PATH: "${SCRUMRL_CONFIG_PATH}"
      # Redis variables (if you decide to use Redis instead of NATS)
      SCRUMLR_SERVER_REDIS_HOST: "${REDIS_HOST}"
      SCRUMLR_SERVER_REDIS_USERNAME: "${REDIS_USERNAME}"
      SCRUMLR_SERVER_REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats

  scrumlr-frontend:
    restart: always
    image: scrumlr.io/scrumlr-frontend:v3.7.1

    environment:
      SCRUMLR_SERVER_URL: "${SCRUMLR_SERVER_URL}"
      SCRUMLR_WEBSOCKET_URL: "${SCRUMLR_WEBSOCKET_URL}"
      SCRUMLR_SHOW_LEGAL_DOCUMENTS: "${SCRUMLR_SHOW_LEGAL_DOCUMENTS}"
      # Add missing frontend environment variables here
      SCRUMLR_LISTEN_PORT: "${SCRUMLR_LISTEN_PORT}"
      SCRUMLR_ANALYTICS_DATA_DOMAIN: "${ANALYTICS_DATA_DOMAIN}"
      SCRUMLR_ANALYTICS_SRC: "${ANALYTICS_SRC}"
    ports:
      - "9090:8080"

  postgres:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_DB: scrumlr
      POSTGRES_USER: scrumlr
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    restart: always
    image: nats:2.8.4
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:
```
You can check our deployment guide here:
https://docs.scrumlr.io/self-hosting/docker/
This will also instruct you on how to set the JWT secret correctly :)
We have a documentation of all variables here:
https://docs.scrumlr.io/self-hosting/env-vars/

**Reply by Lennart01** [reply]
Also note that should you be on an ARM arch we currently do not build images for ARM yet.
We try to get that into the next release but for now you would need to build our docker files.

**Reply by jbesclapez** [reply]
Hi Lennart!

Thank you for your reply, it is greatly appreciated.
I tried with the docker compose you sent me, but i get a 404 error. I tried to use 
`docker login scrumlr.io`
but it did not work too...

I cloned your git on my local and updated the docker compose this way : 

```
version: '3.8'

services:
  scrumlr-backend:
    restart: always
    build:
      context: ./server/src/
      dockerfile: Dockerfile
    command:
      - "/app/main"
      - "-disable-check-origin"
    environment:
      SCRUMLR_SERVER_PORT: "${SCRUMLR_SERVER_PORT}"
      SCRUMLR_SERVER_NATS_URL: "${SCRUMLR_SERVER_NATS_URL}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # Added this line to ensure DB password is available
      SCRUMLR_SERVER_DATABASE_URL: "postgres://scrumlr:${POSTGRES_PASSWORD}@postgres:5432/scrumlr?sslmode=disable" # Added to fix DB URL

      SCRUMLR_PRIVATE_KEY: "${SCRUMLR_PRIVATE_KEY}"
      #SCRUMLR_AUTH_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      #SCRUMLR_AUTH_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      #SCRUMLR_AUTH_MICROSOFT_CLIENT_ID: "${MICROSOFT_CLIENT_ID}"
      #SCRUMLR_AUTH_MICROSOFT_CLIENT_SECRET: "${MICROSOFT_CLIENT_SECRET}"
      #SCRUMLR_FEEDBACK_WEBHOOK_URL: "${WEBHOOK_URL}"
      #SCRUMLR_BASE_PATH: "${SCRUMLR_BASE_PATH}"
      SCRUMLR_INSECURE: "${SCRUMLR_INSECURE}"
      #SCRUMLR_AUTH_GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      #SCRUMLR_AUTH_GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      #SCRUMLR_AUTH_AZURE_AD_TENANT_ID: "${AZURE_AD_TENANT_ID}"
      #SCRUMLR_AUTH_AZURE_AD_CLIENT_ID: "${AZURE_AD_CLIENT_ID}"
      #SCRUMLR_AUTH_AZURE_AD_CLIENT_SECRET: "${AZURE_AD_CLIENT_SECRET}"
      #SCRUMLR_AUTH_APPLE_CLIENT_ID: "${APPLE_CLIENT_ID}"
      #SCRUMLR_AUTH_APPLE_CLIENT_SECRET: "${APPLE_CLIENT_SECRET}"
      # SCRUMLR_CONFIG_PATH: "${SCRUMRL_CONFIG_PATH}"
      # Redis variables (if you decide to use Redis instead of NATS)
      #SCRUMLR_SERVER_REDIS_HOST: "${REDIS_HOST}"
      #SCRUMLR_SERVER_REDIS_USERNAME: "${REDIS_USERNAME}"
      #SCRUMLR_SERVER_REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats

  scrumlr-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SCRUMLR_SERVER_URL: "${SCRUMLR_SERVER_URL}"
      SCRUMLR_WEBSOCKET_URL: "${SCRUMLR_WEBSOCKET_URL}"
      SCRUMLR_SHOW_LEGAL_DOCUMENTS: "${SCRUMLR_SHOW_LEGAL_DOCUMENTS}"
      # Add missing frontend environment variables here
      SCRUMLR_LISTEN_PORT: "${SCRUMLR_LISTEN_PORT}"
      #SCRUMLR_ANALYTICS_DATA_DOMAIN: "${ANALYTICS_DATA_DOMAIN}"
      #SCRUMLR_ANALYTICS_SRC: "${ANALYTICS_SRC}"
    ports:
      - "9090:8080"

  postgres:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_DB: scrumlr
      POSTGRES_USER: scrumlr
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    restart: always
    image: nats:2.8.4
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:

```

And my env file is like this :


```
PUBLIC_URL=/
REACT_APP_PUBLIC_URL=/
REACT_APP_VERSION=$npm_package_version  
# Your Postgres Password
POSTGRES_PASSWORD=testtest123987
# Server Port
SCRUMLR_SERVER_PORT=8080
# Server URL
SCRUMLR_SERVER_URL="http://localhost:8080/api"
# Show Legal Documents (Cookie Policy, Privacy Policy, Terms of Service)
SCRUMLR_SHOW_LEGAL_DOCUMENTS=true
# Websocket URL (wss:// or ws://)
SCRUMLR_WEBSOCKET_URL="ws://localhost:8080/api"
# Frontend Port
SCRUMLR_LISTEN_PORT=8080
# NATS URL
SCRUMLR_SERVER_NATS_URL="nats://nats:4222"
# Uses the hardcoded insecure key for development
#SCRUMLR_INSECURE=1234567890abcdef
# Show Legal Documents (Cookie Policy, Privacy Policy, Terms of Service)
SCRUMLR_SHOW_LEGAL_DOCUMENTS=false
# JWT Private Key (ECDSA). Generate a new key for PRODUCTION
# Uses the hardcoded insecure key for development
SCRUMLR_PRIVATE_KEY="-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIB1ouwcGTwpozBh+A==\n-----END EC PRIVATE KEY-----"

```

WHen i runit like this, then the containers start, the webpage start, but I seem to get an issue when I update the username with another 404 on my browser :       GET http://localhost:8080/api/user 404 (Not Found)

It could be an error due to nginx. But i do not change nginx from the github.... so what is wrong on my side?

Thanks for your time.
