### DISCUSSION TITLE
net::ERR_BLOCKED_BY_CLIENT - Works on laptop but not on server (only on firefox)

### DISCUSSION THREAD

**Discussion by jbesclapez** [inovex/scrumlr.io#4359] [Q&A]
Hello,

I made my visual changes to Scrumlr and I tested it working on Docker on my laptop. Now I am trying to migrate to my ubuntu server.
All logs seem fine in docker, but in the browser I get :
_auth.ts:56  GET http://localhost:8080/user net::ERR_BLOCKED_BY_CLIENT_

Update : It works on Firefox but not on chrome and edge. I can not believe it!

Any idea?

Thanks

```
version: '3.8'

services:
  scrumlr-backend:
    restart: always
    build:
      context: ./server/src/
      dockerfile: Dockerfile
    #image:  ghcr.io/inovex/scrumlr.io/scrumlr-server
    command:
      - "/app/main"
      - "-disable-check-origin"
    environment:
      SCRUMLR_SERVER_PORT: "${SCRUMLR_SERVER_PORT}"
      SCRUMLR_SERVER_NATS_URL: "${SCRUMLR_SERVER_NATS_URL}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # Added this line to ensure DB password is available
      SCRUMLR_SERVER_DATABASE_URL: "postgres://scrumlr:${POSTGRES_PASSWORD}@postgres:5432/scrumlr?sslmode=disable" # Added to fix DB URL
      SCRUMLR_PRIVATE_KEY: "${SCRUMLR_PRIVATE_KEY}"
      #SCRUMLR_AUTH_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      #SCRUMLR_AUTH_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      #SCRUMLR_AUTH_MICROSOFT_CLIENT_ID: "${MICROSOFT_CLIENT_ID}"
      #SCRUMLR_AUTH_MICROSOFT_CLIENT_SECRET: "${MICROSOFT_CLIENT_SECRET}"
      #SCRUMLR_FEEDBACK_WEBHOOK_URL: "${WEBHOOK_URL}"
      SCRUMLR_BASE_PATH: "${SCRUMLR_BASE_PATH}"
      SCRUMLR_INSECURE: "${SCRUMLR_INSECURE}"
      #SCRUMLR_AUTH_GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      #SCRUMLR_AUTH_GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      #SCRUMLR_AUTH_AZURE_AD_TENANT_ID: "${AZURE_AD_TENANT_ID}"
      #SCRUMLR_AUTH_AZURE_AD_CLIENT_ID: "${AZURE_AD_CLIENT_ID}"
      #SCRUMLR_AUTH_AZURE_AD_CLIENT_SECRET: "${AZURE_AD_CLIENT_SECRET}"
      #SCRUMLR_AUTH_APPLE_CLIENT_ID: "${APPLE_CLIENT_ID}"
      #SCRUMLR_AUTH_APPLE_CLIENT_SECRET: "${APPLE_CLIENT_SECRET}"
      # SCRUMLR_CONFIG_PATH: "${SCRUMRL_CONFIG_PATH}"
      # Redis variables (if you decide to use Redis instead of NATS)
      #SCRUMLR_SERVER_REDIS_HOST: "${REDIS_HOST}"
      #SCRUMLR_SERVER_REDIS_USERNAME: "${REDIS_USERNAME}"
      #SCRUMLR_SERVER_REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats

  scrumlr-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/inovex/scrumlr.io/scrumlr-frontend
    environment:
      SCRUMLR_SERVER_URL: "${SCRUMLR_SERVER_URL}"
      SCRUMLR_WEBSOCKET_URL: "${SCRUMLR_WEBSOCKET_URL}"
      SCRUMLR_SHOW_LEGAL_DOCUMENTS: "${SCRUMLR_SHOW_LEGAL_DOCUMENTS}"
      # Add missing frontend environment variables here
      SCRUMLR_LISTEN_PORT: "${SCRUMLR_LISTEN_PORT}"
      #SCRUMLR_ANALYTICS_DATA_DOMAIN: "${ANALYTICS_DATA_DOMAIN}"
      #SCRUMLR_ANALYTICS_SRC: "${ANALYTICS_SRC}"
    ports:
      - "9090:8080"

  postgres:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_DB: scrumlr
      POSTGRES_USER: scrumlr
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    restart: always
    image: nats:2.8.4
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:
```

And the env file

```
 PUBLIC_URL=/
REACT_APP_PUBLIC_URL=/
REACT_APP_VERSION=$npm_package_version
# Your Postgres Password
POSTGRES_PASSWORD=testtest123987
# Server Port
SCRUMLR_SERVER_PORT=8080
# Server URL
SCRUMLR_SERVER_URL="http://localhost:8080"
# Show Legal Documents (Cookie Policy, Privacy Policy, Terms of Service)
SCRUMLR_SHOW_LEGAL_DOCUMENTS=true
# Websocket URL (wss:// or ws://)
SCRUMLR_WEBSOCKET_URL="ws://localhost:8080"
# Frontend Port
SCRUMLR_LISTEN_PORT=8080
# NATS URL
SCRUMLR_SERVER_NATS_URL="nats://nats:4222"
# Uses the hardcoded insecure key for development
#SCRUMLR_INSECURE=1234567890abcdef
# Show Legal Documents (Cookie Policy, Privacy Policy, Terms of Service)
SCRUMLR_SHOW_LEGAL_DOCUMENTS=false
# JWT Private Key (ECDSA). Generate a new key for PRODUCTION
SCRUMLR_BASE_PATH="/api"
# Uses the hardcoded insecure key for development
SCRUMLR_PRIVATE_KEY="-----BEGIN EC PRIVATE KEY-----\nMIHcA+A==\n-----END EC PRIVATE KEY-----"
```
